package ram.gameport.service.matrix.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.service.BaseServiceImpl;
import com.liferay.portal.service.persistence.UserPersistence;

import ram.gameport.service.matrix.model.Matrix;
import ram.gameport.service.matrix.service.MatrixService;
import ram.gameport.service.matrix.service.persistence.MatrixPersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the matrix remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link ram.gameport.service.matrix.service.impl.MatrixServiceImpl}.
 * </p>
 *
 * @author gameport
 * @see ram.gameport.service.matrix.service.impl.MatrixServiceImpl
 * @see ram.gameport.service.matrix.service.MatrixServiceUtil
 * @generated
 */
public abstract class MatrixServiceBaseImpl extends BaseServiceImpl
    implements MatrixService, IdentifiableBean {
    @BeanReference(type = ram.gameport.service.matrix.service.MatrixLocalService.class)
    protected ram.gameport.service.matrix.service.MatrixLocalService matrixLocalService;
    @BeanReference(type = ram.gameport.service.matrix.service.MatrixService.class)
    protected ram.gameport.service.matrix.service.MatrixService matrixService;
    @BeanReference(type = MatrixPersistence.class)
    protected MatrixPersistence matrixPersistence;
    @BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
    protected com.liferay.counter.service.CounterLocalService counterLocalService;
    @BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
    protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
    @BeanReference(type = com.liferay.portal.service.UserLocalService.class)
    protected com.liferay.portal.service.UserLocalService userLocalService;
    @BeanReference(type = com.liferay.portal.service.UserService.class)
    protected com.liferay.portal.service.UserService userService;
    @BeanReference(type = UserPersistence.class)
    protected UserPersistence userPersistence;
    private String _beanIdentifier;
    private ClassLoader _classLoader;
    private MatrixServiceClpInvoker _clpInvoker = new MatrixServiceClpInvoker();

    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. Always use {@link ram.gameport.service.matrix.service.MatrixServiceUtil} to access the matrix remote service.
     */

    /**
     * Returns the matrix local service.
     *
     * @return the matrix local service
     */
    public ram.gameport.service.matrix.service.MatrixLocalService getMatrixLocalService() {
        return matrixLocalService;
    }

    /**
     * Sets the matrix local service.
     *
     * @param matrixLocalService the matrix local service
     */
    public void setMatrixLocalService(
        ram.gameport.service.matrix.service.MatrixLocalService matrixLocalService) {
        this.matrixLocalService = matrixLocalService;
    }

    /**
     * Returns the matrix remote service.
     *
     * @return the matrix remote service
     */
    public ram.gameport.service.matrix.service.MatrixService getMatrixService() {
        return matrixService;
    }

    /**
     * Sets the matrix remote service.
     *
     * @param matrixService the matrix remote service
     */
    public void setMatrixService(
        ram.gameport.service.matrix.service.MatrixService matrixService) {
        this.matrixService = matrixService;
    }

    /**
     * Returns the matrix persistence.
     *
     * @return the matrix persistence
     */
    public MatrixPersistence getMatrixPersistence() {
        return matrixPersistence;
    }

    /**
     * Sets the matrix persistence.
     *
     * @param matrixPersistence the matrix persistence
     */
    public void setMatrixPersistence(MatrixPersistence matrixPersistence) {
        this.matrixPersistence = matrixPersistence;
    }

    /**
     * Returns the counter local service.
     *
     * @return the counter local service
     */
    public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
        return counterLocalService;
    }

    /**
     * Sets the counter local service.
     *
     * @param counterLocalService the counter local service
     */
    public void setCounterLocalService(
        com.liferay.counter.service.CounterLocalService counterLocalService) {
        this.counterLocalService = counterLocalService;
    }

    /**
     * Returns the resource local service.
     *
     * @return the resource local service
     */
    public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
        return resourceLocalService;
    }

    /**
     * Sets the resource local service.
     *
     * @param resourceLocalService the resource local service
     */
    public void setResourceLocalService(
        com.liferay.portal.service.ResourceLocalService resourceLocalService) {
        this.resourceLocalService = resourceLocalService;
    }

    /**
     * Returns the user local service.
     *
     * @return the user local service
     */
    public com.liferay.portal.service.UserLocalService getUserLocalService() {
        return userLocalService;
    }

    /**
     * Sets the user local service.
     *
     * @param userLocalService the user local service
     */
    public void setUserLocalService(
        com.liferay.portal.service.UserLocalService userLocalService) {
        this.userLocalService = userLocalService;
    }

    /**
     * Returns the user remote service.
     *
     * @return the user remote service
     */
    public com.liferay.portal.service.UserService getUserService() {
        return userService;
    }

    /**
     * Sets the user remote service.
     *
     * @param userService the user remote service
     */
    public void setUserService(
        com.liferay.portal.service.UserService userService) {
        this.userService = userService;
    }

    /**
     * Returns the user persistence.
     *
     * @return the user persistence
     */
    public UserPersistence getUserPersistence() {
        return userPersistence;
    }

    /**
     * Sets the user persistence.
     *
     * @param userPersistence the user persistence
     */
    public void setUserPersistence(UserPersistence userPersistence) {
        this.userPersistence = userPersistence;
    }

    public void afterPropertiesSet() {
        Class<?> clazz = getClass();

        _classLoader = clazz.getClassLoader();
    }

    public void destroy() {
    }

    /**
     * Returns the Spring bean ID for this bean.
     *
     * @return the Spring bean ID for this bean
     */
    @Override
    public String getBeanIdentifier() {
        return _beanIdentifier;
    }

    /**
     * Sets the Spring bean ID for this bean.
     *
     * @param beanIdentifier the Spring bean ID for this bean
     */
    @Override
    public void setBeanIdentifier(String beanIdentifier) {
        _beanIdentifier = beanIdentifier;
    }

    @Override
    public Object invokeMethod(String name, String[] parameterTypes,
        Object[] arguments) throws Throwable {
        Thread currentThread = Thread.currentThread();

        ClassLoader contextClassLoader = currentThread.getContextClassLoader();

        if (contextClassLoader != _classLoader) {
            currentThread.setContextClassLoader(_classLoader);
        }

        try {
            return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
        } finally {
            if (contextClassLoader != _classLoader) {
                currentThread.setContextClassLoader(contextClassLoader);
            }
        }
    }

    protected Class<?> getModelClass() {
        return Matrix.class;
    }

    protected String getModelClassName() {
        return Matrix.class.getName();
    }

    /**
     * Performs an SQL query.
     *
     * @param sql the sql query
     */
    protected void runSQL(String sql) throws SystemException {
        try {
            DataSource dataSource = matrixPersistence.getDataSource();

            SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
                    sql, new int[0]);

            sqlUpdate.update();
        } catch (Exception e) {
            throw new SystemException(e);
        }
    }
}
