package ram.gameport.service.matrix.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Matrix service. Represents a row in the &quot;matrixService_Matrix&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ram.gameport.service.matrix.model.impl.MatrixModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ram.gameport.service.matrix.model.impl.MatrixImpl}.
 * </p>
 *
 * @author gameport
 * @see Matrix
 * @see ram.gameport.service.matrix.model.impl.MatrixImpl
 * @see ram.gameport.service.matrix.model.impl.MatrixModelImpl
 * @generated
 */
public interface MatrixModel extends BaseModel<Matrix> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a matrix model instance should use the {@link Matrix} interface instead.
     */

    /**
     * Returns the primary key of this matrix.
     *
     * @return the primary key of this matrix
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this matrix.
     *
     * @param primaryKey the primary key of this matrix
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the matrix ID of this matrix.
     *
     * @return the matrix ID of this matrix
     */
    public long getMatrixId();

    /**
     * Sets the matrix ID of this matrix.
     *
     * @param matrixId the matrix ID of this matrix
     */
    public void setMatrixId(long matrixId);

    /**
     * Returns the matrix name of this matrix.
     *
     * @return the matrix name of this matrix
     */
    @AutoEscape
    public String getMatrixName();

    /**
     * Sets the matrix name of this matrix.
     *
     * @param matrixName the matrix name of this matrix
     */
    public void setMatrixName(String matrixName);

    /**
     * Returns the position x of this matrix.
     *
     * @return the position x of this matrix
     */
    public int getPositionX();

    /**
     * Sets the position x of this matrix.
     *
     * @param positionX the position x of this matrix
     */
    public void setPositionX(int positionX);

    /**
     * Returns the position y of this matrix.
     *
     * @return the position y of this matrix
     */
    public int getPositionY();

    /**
     * Sets the position y of this matrix.
     *
     * @param positionY the position y of this matrix
     */
    public void setPositionY(int positionY);

    /**
     * Returns the data type of this matrix.
     *
     * @return the data type of this matrix
     */
    @AutoEscape
    public String getDataType();

    /**
     * Sets the data type of this matrix.
     *
     * @param dataType the data type of this matrix
     */
    public void setDataType(String dataType);

    /**
     * Returns the data value of this matrix.
     *
     * @return the data value of this matrix
     */
    @AutoEscape
    public String getDataValue();

    /**
     * Sets the data value of this matrix.
     *
     * @param dataValue the data value of this matrix
     */
    public void setDataValue(String dataValue);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(Matrix matrix);

    @Override
    public int hashCode();

    @Override
    public CacheModel<Matrix> toCacheModel();

    @Override
    public Matrix toEscapedModel();

    @Override
    public Matrix toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
